download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/drew1kun-shellfreak-1.1.18.tar.gz
format_version: 1.0.0
name: shellfreak
namespace: drew1kun
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.1.18
version_url: /api/v3/plugin/ansible/content/published/collections/index/drew1kun/shellfreak/versions/1.1.18/
