FROM docker.io/andygodish/base-python:3.11-slim-bookworm

USER root

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends openssh-client sshpass && \
    apt autoremove -y && \
    apt clean -y && \
    rm -rf /var/lib/apt/lists/*

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog

USER appuser

RUN pip install pip --upgrade
RUN pip install --user ansible

ENV PATH="/home/appuser/.local/bin:${PATH}"

# Additional Ansible configuration
RUN mkdir -p /home/appuser/.ssh && \
    mkdir -p /home/appuser/.ansible/roles /home/appuser/.ansible/tmp 
