---
- name: '[config] Find bash binary for correct shell tmux version check'
  ansible.builtin.command: which bash
  register: tmux_bash_bin
  changed_when: false

- name: '[config] Check the tmux version'
  # set -o pipefail && tmux -V | ... - not required anymore
  ansible.builtin.shell: tmux -V | tr -d '[A-Z][a-z][ ]'
  args:
    executable: "{{ tmux_bash_bin.stdout }}"
  register: tmux_version
  changed_when: false

- name: '[config] Generate tmux custom configuration'
  ansible.builtin.template:
    src: tmux.conf.j2
    dest: "{{ tmux_root_dir if item == 'root' else tmux_home_dir ~ item }}/.tmux.conf"
    mode: 0644
    owner: "{{ item }}"
    group: >-
      {{
        item if 'Darwin' not in ansible_os_family else
        'wheel' if item == 'root' else 'staff'
      }}
  when: "item.state is not defined or 'present'in item.state"
  loop: "{{ tmux_users|flatten(levels=1) }}"
  become: true
