name: Build 'docker.io/python' Base Images
on:
  workflow_dispatch:
  # Executes on the 13th of every month at 1pm UTC
  schedule:
    - cron: '0 13 13 * *'
env: 
  # The build.sh script takes in a variable corresponding to a directory and builds all dockerfiles in that folder
  BASE_DIR: python
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build docker.io/python base images
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make the build.sh script executable
      run: chmod +x build.sh

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push docker images
      run: ./build.sh ${{ env.BASE_DIR }}